name: API Auto Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum

      # Use golangci-lint-action
      # - name: Run golangci-lint
      #   uses: golangci/golangci-lint-action@v7
      #   with:
      #     version: v2.0
      #     args: ./api/...

      - name: Run Go tests
        run: |
          cd api
          go test -race -cover ./...
